/**
 * Bridge to Helix (https://github.com/KE7/helix, `pip install helix-evo`),
 * which evolves a whole repository: coding-agent CLIs mutate copies in git
 * worktrees under `.helix/worktrees/` on `helix/*` branches, an evaluator
 * scores each candidate, and a Pareto frontier keeps the best. Helix never
 * touches the working branch, so evolution is sandboxed by construction.
 *
 * This module only renders config, builds commands and parses evaluator
 * output; the `helix.toml` keys are passed through, so any upstream option
 * can be set without code changes.
 *
 * @module dsh-evolution/helix
 */

export type TomlValue = string | number | boolean | readonly TomlValue[] | { [key: string]: TomlValue }

const bare = /^[A-Za-z0-9_-]+$/
const k = (key: string): string => (bare.test(key) ? key : JSON.stringify(key))

function scalar(v: TomlValue): string {
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) return `[${v.map(scalar).join(', ')}]`
  return `{ ${Object.entries(v as Record<string, TomlValue>).map(([kk, vv]) => `${k(kk)} = ${scalar(vv)}`).join(', ')} }`
}

const isTable = (v: TomlValue): v is { [key: string]: TomlValue } => typeof v === 'object' && !Array.isArray(v)

/** Minimal TOML writer: scalars and arrays inline, nested objects as [tables]. */
export function toToml(doc: { [key: string]: TomlValue }, prefix = ''): string {
  const lines: string[] = []
  const tables: [string, { [key: string]: TomlValue }][] = []
  for (const [key, value] of Object.entries(doc)) {
    if (isTable(value)) tables.push([prefix ? `${prefix}.${k(key)}` : k(key), value])
    else lines.push(`${k(key)} = ${scalar(value)}`)
  }
  let out = lines.join('\n')
  for (const [name, table] of tables) out += `${out ? '\n\n' : ''}[${name}]\n${toToml(table, name)}`.replace(/\n\n\[/g, '\n\n[')
  return out.replace(/\n{3,}/g, '\n\n')
}

export interface HelixCommandOptions {
  config?: string | undefined
  extra?: readonly string[] | undefined
}

export function helixCommand(action: 'evolve' | 'resume' | 'clean', options: HelixCommandOptions = {}): string[] {
  return ['helix', action, ...options.config ? ['--config', options.config] : [], ...options.extra ?? []]
}

export interface HelixResult {
  /** Primary score (higher is better). */
  score: number
  /** Extra objectives for the Pareto frontier. */
  metrics: Record<string, number>
  raw: unknown
}

/**
 * Parse the evaluator contract: the last line starting with `HELIX_RESULT`
 * followed by JSON (an object with `score`, or a bare number).
 */
export function parseHelixResult(output: string): HelixResult | undefined {
  const line = output.split('\n').reverse().find((l) => l.trimStart().startsWith('HELIX_RESULT'))
  if (!line) return undefined
  const payload = line.trimStart().slice('HELIX_RESULT'.length).replace(/^[\s:=]+/, '')
  let raw: unknown
  try { raw = JSON.parse(payload) } catch { return undefined }
  if (typeof raw === 'number') return { score: raw, metrics: {}, raw }
  if (!raw || typeof raw !== 'object') return undefined
  const obj = raw as Record<string, unknown>
  const metrics: Record<string, number> = {}
  for (const [key, v] of Object.entries(obj)) if (typeof v === 'number' && key !== 'score') metrics[key] = v
  const score = typeof obj.score === 'number' ? obj.score : Object.values(metrics)[0]
  return score === undefined ? undefined : { score, metrics, raw }
}

/**
 * A POSIX evaluator script: runs each gate command, fails the candidate if a
 * required gate fails, and prints `HELIX_RESULT {"score": passed/total, ...}`.
 */
export function evaluatorScript(gates: readonly { name: string, command: string, required?: boolean }[]): string {
  const body = gates.map((g, i) => [
    `if sh -c ${shq(g.command)} >/tmp/helix-gate-${i}.log 2>&1; then passed=$((passed+1)); m="$m, \\"${g.name}\\": 1"; else m="$m, \\"${g.name}\\": 0";${g.required === false ? '' : ' failed_required=1;'} fi`,
  ].join('\n')).join('\n')
  return `#!/bin/sh
# Generated by @deepseek-ai/dsh-evolution. Scores a Helix candidate.
passed=0; total=${gates.length}; failed_required=0; m=""
${body}
if [ "$failed_required" = 1 ]; then score=0; else score=$(awk "BEGIN { print $passed / $total }"); fi
echo "HELIX_RESULT {\\"score\\": $score$m}"
`
}

const shq = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`
